/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Mom' at '2/8/16 4:05 PM' with Gradle 2.6
 *
 * @author Mom, @date 2/8/16 4:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
